UI_EMOJI = {
    "myday": "☀️",
    "leisure": "🍿",
    "cinema": "🎬",
    "books": "📖",
    "music": "🎧",
    "concerts": "🎸",
    "wardrobe": "👟",
    "clothes": "👕",
    "food": "🥣",
    "recipes": "🍽",
    "version": "🚀",
    "products": "🧊",
    "cook_from": "🥕",
    "learning": "📚",
    "dictionary": "🗂️",
    "phrases": "🧩",
    "live_language": "💭",
    "word_trainer": "🧠",
    "travel": "✈️",
    "countries": "🌍",
    "routes": "🗺",
    "health": "🚑",
    "doctor": "👩🏻‍⚕️",
    "worry_diary": "📓",
    "health_history": "📋",
    "recommendation": "✨",
    "save": "⭐️",
    "favorite": "❤️",
    "settings": "🎚️",
    "breakfast": "🥐",
    "lunch": "🥗",
    "dinner": "🍲",
    "add": "✏️",
    "delete": "❌",
    "find": "🔍",
    "seen": "✅",
    "warning": "⚠️",
    "hot": "🔥",
    "interesting": "👨🏻‍💻",
    "news": "📰",
    "system": "📊",
    "users": "👥",
    "logs": "📈",
    "invite": "🔗",
    "refresh": "🔄",
    "status_ok": "🟢",
    "status_warn": "🟡",
    "status_bad": "🔴",
    "admin": "🛠️",
    "welcome": "👋",
    "diagnostics": "📊",
    "api": "🔌",
    "llm": "🤖",
    "notifications": "🔔",
    "tests": "🧪",
    "history": "📜",
    "profile": "👤",
    "broadcasts": "📬",
    "priorities": "🎯",
    "cuisines": "🍽",
    "clothing_style": "👟",
    "personal_data": "👤",
    "lagom": "🌿",
    "examples": "💬",
    "sections": "📂",
    "translation": "🔤",
    "usage": "💭",
    "example": "💬",
    "knowledge": "🦉",
    "quote": "💬",
    "worries": "📓",
    "evening": "🌙",
    "summary": "✅",
    "assessment": "✨",
    "shopping": "🛍️",
    "avoid": "⚠️",
    "potential": "✨",
    "why_today": "☀️",
    "empty_wardrobe": "👕",
    "when": "🕒",
    "action": "✅",
    "week": "🗓️",
    "reason": "✨",
    "spoken_language": "🗣️",
    "best_time": "🕒",
    "budget": "💶",
    "dont_miss": "❗️",
    "lgbtq": "🌈",
}

CUISINE_EMOJI = {
    "asian": "🥢",
    "russian": "🇷🇺",
    "italian": "🇮🇹",
    "mediterranean": "🫒",
    "mexican": "🇲🇽",
    "french": "🇫🇷",
    "japanese": "🇯🇵",
    "korean": "🇰🇷",
    "chinese": "🇨🇳",
    "thai": "🇹🇭",
    "vietnamese": "🇻🇳",
    "indian": "🇮🇳",
    "turkish": "🇹🇷",
    "greek": "🇬🇷",
    "spanish": "🇪🇸",
    "german": "🇩🇪",
    "american": "🇺🇸",
    "georgian": "🇬🇪",
}

LANGUAGE_EMOJI = {
    "nl": "🇳🇱",
    "en": "🇬🇧",
}

COUNTRY_EMOJI = {
    "nl": "🇳🇱",
    "be": "🇧🇪",
    "de": "🇩🇪",
    "fr": "🇫🇷",
    "gb": "🇬🇧",
    "es": "🇪🇸",
    "it": "🇮🇹",
    "at": "🇦🇹",
    "ch": "🇨🇭",
    "pl": "🇵🇱",
    "se": "🇸🇪",
    "dk": "🇩🇰",
    "pt": "🇵🇹",
}

WEATHER_EMOJI = {
    "sun": "☀️",
    "cloud": "☁️",
    "rain": "🌧️",
    "storm": "⛈️",
    "thunderstorm": "🌩️",
    "snow": "❄️",
    "fog": "🌫️",
    "wind": "💨",
    "temperature": "🌡️",
    "humidity": "💧",
    "wind_direction": "🌬️",
    "heat": "🥵",
    "cold": "🥶",
    "tornado": "🌪️",
    "waves": "🌊",
}

STATUS_EMOJI = {
    "ok": UI_EMOJI["status_ok"],
    "warn": UI_EMOJI["status_warn"],
    "bad": UI_EMOJI["status_bad"],
}


def ui_label(key, text):
    emoji = UI_EMOJI.get(key)
    return f"{emoji} {text}" if emoji else text


def cuisine_label(key, text):
    emoji = CUISINE_EMOJI.get(key)
    return f"{emoji} {text}" if emoji else text


def language_label(code, text):
    emoji = LANGUAGE_EMOJI.get(code)
    return f"{emoji} {text}" if emoji else text
